"use client";

import { jsPDF } from "jspdf";
import type { QuizProfile } from "./store";

const STYLE_LABELS: Record<string, string> = {
  "modern-minimalist": "Modern Minimalist",
  "warm-organic": "Warm Organic",
  "scandinavian-functional": "Scandinavian Functional",
  "industrial-loft": "Industrial Loft",
  "traditional-romanian": "Traditional Romanian",
  "biophilic-nature": "Biophilic / Nature-First",
  "eclectic-mixed": "Eclectic Mixed",
};

/**
 * Generate a PDF summary of the user's architectural profile quiz results.
 */
export function exportQuizProfilePdf(profile: QuizProfile) {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const w = doc.internal.pageSize.getWidth();
  let y = 20;

  const olive = [74, 93, 54] as const; // brand-olive-700 approx
  const charcoal = [38, 38, 38] as const;
  const gray = [120, 120, 120] as const;

  // ---- Header ----
  doc.setFillColor(...olive);
  doc.rect(0, 0, w, 45, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text("ModulCA", 15, 18);

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("Architectural Profile Report", 15, 26);

  doc.setFontSize(8);
  doc.text(`Generated: ${new Date().toLocaleDateString("en-GB")}`, 15, 34);
  doc.text("modulca.eu", w - 15, 34, { align: "right" });

  y = 55;

  // ---- Primary Style ----
  doc.setTextColor(...charcoal);
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("PRIMARY STYLE", 15, y);
  y += 7;

  doc.setFontSize(18);
  doc.text(STYLE_LABELS[profile.primaryStyle] ?? profile.primaryStyle, 15, y);
  y += 7;

  if (profile.secondaryStyles.length > 0) {
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...gray);
    doc.text(
      `With influences from: ${profile.secondaryStyles.map((s) => STYLE_LABELS[s] ?? s).join(", ")}`,
      15,
      y,
    );
    y += 5;
  }

  y += 8;

  // ---- Key Metrics ----
  doc.setTextColor(...charcoal);
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("KEY METRICS", 15, y);
  y += 8;

  const metrics = [
    ["Household", `${profile.householdSize} people`],
    ["Modules", `${profile.totalModules} modules (${profile.grossArea}m\u00B2 gross / ${profile.usableArea}m\u00B2 usable)`],
    ["Layout", profile.layout],
    ["Budget Level", profile.budgetLevel],
    ["Sustainability", `${profile.sustainability}/5`],
    ["Biophilic Affinity", `${profile.biophilic}/5`],
  ];

  doc.setFontSize(10);
  for (const [label, value] of metrics) {
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...charcoal);
    doc.text(`${label}:`, 15, y);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...gray);
    doc.text(value, 55, y);
    y += 6;
  }

  y += 8;

  // ---- Recommended Materials ----
  doc.setTextColor(...charcoal);
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("RECOMMENDED MATERIALS", 15, y);
  y += 8;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...gray);
  const matLine = profile.materials.join("  |  ");
  doc.text(matLine, 15, y, { maxWidth: w - 30 });
  y += 10;

  // ---- Module Visualization ----
  y += 5;
  doc.setTextColor(...charcoal);
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("MODULE LAYOUT ESTIMATE", 15, y);
  y += 8;

  // Draw module grid
  const moduleSize = 12;
  const gap = 2;
  const cols = Math.min(profile.totalModules, 6);
  const rows = Math.ceil(profile.totalModules / cols);
  const gridStartX = 15;

  for (let r = 0; r < rows; r++) {
    for (let c = 0; c < cols; c++) {
      const idx = r * cols + c;
      if (idx >= profile.totalModules) break;
      const x = gridStartX + c * (moduleSize + gap);
      const my = y + r * (moduleSize + gap);
      doc.setFillColor(...olive);
      doc.roundedRect(x, my, moduleSize, moduleSize, 1, 1, "F");
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(7);
      doc.text(`${idx + 1}`, x + moduleSize / 2, my + moduleSize / 2 + 1, { align: "center" });
    }
  }

  y += rows * (moduleSize + gap) + 5;
  doc.setTextColor(...gray);
  doc.setFontSize(8);
  doc.text(`Each module: 3.00 x 3.00m (9m\u00B2 gross, ~7m\u00B2 usable)`, 15, y);
  y += 4;
  doc.text(`Total: ${profile.totalModules} modules = ${profile.grossArea}m\u00B2 gross / ${profile.usableArea}m\u00B2 usable`, 15, y);

  // ---- Footer ----
  const footerY = doc.internal.pageSize.getHeight() - 15;
  doc.setDrawColor(200, 200, 200);
  doc.line(15, footerY - 5, w - 15, footerY - 5);
  doc.setFontSize(8);
  doc.setTextColor(...gray);
  doc.text("Generated by ModulCA — modulca.eu", 15, footerY);
  doc.text("This is an estimate. Consult a licensed architect for your project.", w - 15, footerY, { align: "right" });

  // ---- Save ----
  doc.save(`modulca-profile-${profile.primaryStyle}.pdf`);
}
