/**
 * ModulCA Asset Registry — Single Source of Truth
 *
 * ALL image URLs and asset references live here.
 * Components import from this file instead of hardcoding URLs.
 *
 * Organization:
 *  - PRODUCT_IMAGES   → Products page (finishing, furniture, plumbing)
 *  - MATERIAL_IMAGES  → Material swatches and textures
 *  - STYLE_IMAGES     → Moodboard, style direction hero/mood images
 *  - PORTFOLIO_IMAGES → Built house photos, case studies
 *  - MODEL_3D         → GLB furniture models mapping
 */

import type { ImageAsset, Model3DAsset, ProductEntry } from "./types";
import { unsplash, model } from "./sources";

/* ═══════════════════════════════════════════════════════════════
   PRODUCT CATALOG — Finishing, Furniture, Plumbing & Electrical
   ═══════════════════════════════════════════════════════════════ */

export const PRODUCT_CATALOG: ProductEntry[] = [
  // ── Finishing Materials (12 products) ─────────────────────
  {
    id: "fin-01",
    name: "Engineered Oak Flooring",
    description: "Wide-plank engineered oak, brushed matte finish, per m\u00B2",
    price: 42,
    unit: "per m\u00B2",
    category: "finishing",
    subcategory: "flooring",
    brand: "Barlinek",
    styles: ["scandinavian", "warm-contemporary"],
    roomTypes: ["bedroom", "living", "office", "hallway"],
    image: {
      id: "fin-01-img",
      name: "Engineered Oak Flooring",
      type: "image",
      category: "material",
      subcategory: "flooring",
      source: "unsplash",
      url: unsplash("1558618666-fcd25c85f82e"),
      color: "#D4A76A",
      format: "jpg",
      tags: ["oak", "flooring", "wood", "engineered"],
    },
    variants: [
      { label: "Natural Oak", color: "#D4A76A" },
      { label: "White Oak", color: "#E8D5B8" },
      { label: "Smoked Oak", color: "#8B6B4A" },
    ],
  },
  {
    id: "fin-02",
    name: "Gypsum Wall Panels",
    description: "Pre-finished gypsum board, smooth white, 120\u00D7240 cm per panel",
    price: 18,
    unit: "per panel",
    category: "finishing",
    subcategory: "wall-finish",
    brand: "Knauf",
    styles: ["scandinavian", "industrial", "warm-contemporary"],
    roomTypes: ["bedroom", "living", "office", "kitchen"],
    image: {
      id: "fin-02-img",
      name: "Gypsum Wall Panels",
      type: "image",
      category: "material",
      subcategory: "wall-finish",
      source: "unsplash",
      url: unsplash("1562259949-e8e7689d7828"),
      color: "#F3F4F6",
      format: "jpg",
      tags: ["gypsum", "wall", "panel", "drywall"],
    },
  },
  {
    id: "fin-03",
    name: "XPS Underfloor Insulation",
    description: "Extruded polystyrene board, 30 mm thick, per m\u00B2",
    price: 12,
    unit: "per m\u00B2",
    category: "finishing",
    subcategory: "insulation",
    brand: "Austrotherm",
    styles: ["scandinavian", "industrial", "warm-contemporary"],
    image: {
      id: "fin-03-img",
      name: "XPS Insulation Board",
      type: "image",
      category: "material",
      subcategory: "insulation",
      source: "unsplash",
      url: unsplash("1607472586893-edb57bdc0e39"),
      color: "#DBEAFE",
      format: "jpg",
      tags: ["insulation", "xps", "thermal", "underfloor"],
    },
  },
  {
    id: "fin-04",
    name: "Triple-Glazed Window Unit",
    description: "PVC frame, argon-filled triple glazing, 120\u00D7140 cm",
    price: 385,
    unit: "per unit",
    category: "finishing",
    subcategory: "window",
    brand: "Rehau",
    styles: ["scandinavian", "industrial", "warm-contemporary"],
    image: {
      id: "fin-04-img",
      name: "Triple-Glazed Window",
      type: "image",
      category: "fixture",
      subcategory: "window",
      source: "unsplash",
      url: unsplash("1497366216548-37526070297c"),
      color: "#CFFAFE",
      format: "jpg",
      tags: ["window", "triple-glazed", "pvc", "energy-efficient"],
    },
  },
  {
    id: "fin-05",
    name: "Interior Flush Door",
    description: "Solid-core flush door, white primed, 80\u00D7200 cm with hardware",
    price: 145,
    unit: "per unit",
    category: "finishing",
    subcategory: "door",
    brand: "Porta Doors",
    image: {
      id: "fin-05-img",
      name: "Interior Flush Door",
      type: "image",
      category: "fixture",
      subcategory: "door",
      source: "unsplash",
      url: unsplash("1506377295352-e3154d43ea9e"),
      color: "#EDE9FE",
      format: "jpg",
      tags: ["door", "interior", "flush", "white"],
    },
  },
  {
    id: "fin-06",
    name: "Mineral Wool Insulation Roll",
    description: "Rock mineral wool, 100 mm thick, fire-rated A1, per m\u00B2",
    price: 8,
    unit: "per m\u00B2",
    category: "finishing",
    subcategory: "insulation",
    brand: "Rockwool",
    image: {
      id: "fin-06-img",
      name: "Mineral Wool Roll",
      type: "image",
      category: "material",
      subcategory: "insulation",
      source: "unsplash",
      url: unsplash("1504307651254-35680f356dfd"),
      color: "#FEF9C3",
      format: "jpg",
      tags: ["insulation", "mineral-wool", "rockwool", "fire-rated"],
    },
  },
  {
    id: "fin-07",
    name: "Interior Wall Paint",
    description: "Low-VOC acrylic emulsion, matt white, 5 L tin covers ~40 m\u00B2",
    price: 35,
    unit: "per 5L tin",
    category: "finishing",
    subcategory: "paint",
    brand: "Dulux",
    image: {
      id: "fin-07-img",
      name: "Interior Wall Paint",
      type: "image",
      category: "material",
      subcategory: "paint",
      source: "unsplash",
      url: unsplash("1589939705384-5185137a7f0f"),
      color: "#D1FAE5",
      format: "jpg",
      tags: ["paint", "wall", "interior", "low-voc"],
    },
  },
  {
    id: "fin-08",
    name: "Porcelain Floor Tiles",
    description: "Rectified porcelain, 60\u00D760 cm, light grey, per m\u00B2",
    price: 28,
    unit: "per m\u00B2",
    category: "finishing",
    subcategory: "tile",
    brand: "Marazzi",
    styles: ["industrial", "warm-contemporary"],
    roomTypes: ["bathroom", "kitchen", "hallway"],
    image: {
      id: "fin-08-img",
      name: "Porcelain Floor Tiles",
      type: "image",
      category: "material",
      subcategory: "tile",
      source: "unsplash",
      url: unsplash("1502672260266-1c1ef2d93688"),
      color: "#F1F5F9",
      format: "jpg",
      tags: ["tile", "porcelain", "floor", "grey"],
    },
  },
  {
    id: "fin-09",
    name: "Vinyl Plank Flooring",
    description: "Waterproof luxury vinyl plank, oak look, click-lock, per m\u00B2",
    price: 22,
    unit: "per m\u00B2",
    category: "finishing",
    subcategory: "flooring",
    brand: "Tarkett",
    styles: ["scandinavian", "warm-contemporary", "industrial"],
    roomTypes: ["kitchen", "bathroom", "hallway"],
    image: {
      id: "fin-09-img",
      name: "Vinyl Plank Flooring",
      type: "image",
      category: "material",
      subcategory: "flooring",
      source: "unsplash",
      url: unsplash("1560185893-39d1d6463bc4"),
      color: "#C9B896",
      format: "jpg",
      tags: ["vinyl", "plank", "flooring", "waterproof"],
    },
    variants: [
      { label: "Light Oak", color: "#D4C4A0" },
      { label: "Grey Oak", color: "#A0A0A0" },
      { label: "Walnut", color: "#6B4A3A" },
    ],
  },
  {
    id: "fin-10",
    name: "Subway Wall Tiles",
    description: "Glossy ceramic subway tiles, 10\u00D720 cm, white, per m\u00B2",
    price: 15,
    unit: "per m\u00B2",
    category: "finishing",
    subcategory: "tile",
    brand: "Cersanit",
    styles: ["scandinavian", "industrial"],
    roomTypes: ["bathroom", "kitchen"],
    image: {
      id: "fin-10-img",
      name: "Subway Wall Tiles",
      type: "image",
      category: "material",
      subcategory: "tile",
      source: "unsplash",
      url: unsplash("1584622781564-1d987f7333c1"),
      color: "#FFFFFF",
      format: "jpg",
      tags: ["subway", "tile", "wall", "ceramic", "white"],
    },
  },
  {
    id: "fin-11",
    name: "Exterior Entrance Door",
    description: "Steel-reinforced composite door, thermal break, with smart lock prep",
    price: 680,
    unit: "per unit",
    category: "finishing",
    subcategory: "door",
    brand: "Porta Doors",
    styles: ["warm-contemporary", "industrial"],
    image: {
      id: "fin-11-img",
      name: "Exterior Entrance Door",
      type: "image",
      category: "fixture",
      subcategory: "door",
      source: "unsplash",
      url: unsplash("1558618047-3c8c76ca7d13"),
      color: "#4A5568",
      format: "jpg",
      tags: ["door", "exterior", "entrance", "steel"],
    },
  },
  {
    id: "fin-12",
    name: "Laminate Kitchen Countertop",
    description: "HPL laminate worktop, marble-look, 60 cm deep, per running metre",
    price: 55,
    unit: "per running m",
    category: "finishing",
    subcategory: "wall-finish",
    brand: "Egger",
    styles: ["scandinavian", "warm-contemporary"],
    roomTypes: ["kitchen"],
    image: {
      id: "fin-12-img",
      name: "Laminate Countertop",
      type: "image",
      category: "material",
      subcategory: "wall-finish",
      source: "unsplash",
      url: unsplash("1556909114-f6e7ad7d3136"),
      color: "#E2E8F0",
      format: "jpg",
      tags: ["countertop", "laminate", "kitchen", "marble-look"],
    },
  },

  // ── Furniture & Decor (12 products) ───────────────────────
  {
    id: "fur-01",
    name: "Modular Sofa 3-Seat",
    description: "Linen-blend upholstery, removable covers, grey",
    price: 1290,
    unit: "per unit",
    category: "furniture",
    subcategory: "seating",
    brand: "Noo.ma",
    styles: ["scandinavian", "warm-contemporary"],
    roomTypes: ["living"],
    image: {
      id: "fur-01-img",
      name: "Modular Sofa",
      type: "image",
      category: "furniture",
      subcategory: "seating",
      source: "unsplash",
      url: unsplash("1555041469-a586c61ea9bc"),
      color: "#F3F4F6",
      format: "jpg",
      tags: ["sofa", "modular", "living", "seating"],
    },
    model3d: {
      id: "fur-01-3d",
      name: "Lounge Sofa",
      type: "model3d",
      category: "furniture",
      subcategory: "seating",
      source: "local",
      modelPath: model("loungeSofa.glb"),
      format: "glb",
      tags: ["sofa", "3d"],
    },
  },
  {
    id: "fur-02",
    name: "Wool Area Rug 200\u00D7300",
    description: "Hand-tufted New Zealand wool, ivory/grey geometric pattern",
    price: 420,
    unit: "per unit",
    category: "furniture",
    subcategory: "textile",
    brand: "Benuta",
    styles: ["scandinavian"],
    roomTypes: ["living", "bedroom"],
    image: {
      id: "fur-02-img",
      name: "Wool Area Rug",
      type: "image",
      category: "furniture",
      subcategory: "textile",
      source: "unsplash",
      url: unsplash("1600166898405-da9535204843"),
      color: "#FEF3C7",
      format: "jpg",
      tags: ["rug", "wool", "textile", "living"],
    },
  },
  {
    id: "fur-03",
    name: "Blackout Curtain Pair",
    description: "Thermal blackout linen-look fabric, 140\u00D7260 cm per panel",
    price: 95,
    unit: "per pair",
    category: "furniture",
    subcategory: "textile",
    styles: ["scandinavian", "warm-contemporary"],
    roomTypes: ["bedroom", "living"],
    image: {
      id: "fur-03-img",
      name: "Blackout Curtains",
      type: "image",
      category: "furniture",
      subcategory: "textile",
      source: "unsplash",
      url: unsplash("1513694203232-719a280e022f"),
      color: "#EDE9FE",
      format: "jpg",
      tags: ["curtain", "blackout", "textile", "bedroom"],
    },
  },
  {
    id: "fur-04",
    name: "Ceramic Vase Collection",
    description: "Set of 3 matte stoneware vases, earth tones, 12\u201322 cm",
    price: 65,
    unit: "per set",
    category: "furniture",
    subcategory: "decor",
    styles: ["scandinavian", "warm-contemporary"],
    image: {
      id: "fur-04-img",
      name: "Ceramic Vases",
      type: "image",
      category: "furniture",
      subcategory: "decor",
      source: "unsplash",
      url: unsplash("1610701596061-2ecf227e85b2"),
      color: "#FEE2E2",
      format: "jpg",
      tags: ["vase", "ceramic", "decor", "stoneware"],
    },
  },
  {
    id: "fur-05",
    name: "Wall-Mounted Shelving Unit",
    description: "Modular oak veneer shelves on steel frame, 80\u00D730\u00D7200 cm",
    price: 280,
    unit: "per unit",
    category: "furniture",
    subcategory: "storage",
    brand: "String Furniture",
    styles: ["scandinavian", "industrial"],
    roomTypes: ["living", "office"],
    image: {
      id: "fur-05-img",
      name: "Wall Shelving Unit",
      type: "image",
      category: "furniture",
      subcategory: "storage",
      source: "unsplash",
      url: unsplash("1594620302200-9a762244a156"),
      color: "#FEF3C7",
      format: "jpg",
      tags: ["shelf", "storage", "wall-mounted", "oak"],
    },
  },
  {
    id: "fur-06",
    name: "Pendant Light Fixture",
    description: "Brass fitting, opal glass dome shade, 28 cm diameter",
    price: 175,
    unit: "per unit",
    category: "furniture",
    subcategory: "lighting",
    styles: ["scandinavian", "warm-contemporary"],
    roomTypes: ["living", "kitchen", "bedroom"],
    image: {
      id: "fur-06-img",
      name: "Pendant Light",
      type: "image",
      category: "furniture",
      subcategory: "lighting",
      source: "unsplash",
      url: unsplash("1513506003901-1e6a229e2d15"),
      color: "#FEF9C3",
      format: "jpg",
      tags: ["pendant", "light", "brass", "lighting"],
    },
  },
  {
    id: "fur-07",
    name: "Round Wall Mirror",
    description: "Brushed brass frame, 80 cm diameter, bevelled edge",
    price: 210,
    unit: "per unit",
    category: "furniture",
    subcategory: "decor",
    styles: ["scandinavian", "warm-contemporary"],
    roomTypes: ["bathroom", "hallway", "bedroom"],
    image: {
      id: "fur-07-img",
      name: "Round Wall Mirror",
      type: "image",
      category: "furniture",
      subcategory: "decor",
      source: "unsplash",
      url: unsplash("1618220179428-22790b461013"),
      color: "#FDE68A",
      format: "jpg",
      tags: ["mirror", "brass", "round", "decor"],
    },
  },
  {
    id: "fur-08",
    name: "Upholstered Dining Chair",
    description: "Boucle fabric seat, solid oak legs, set of 2",
    price: 195,
    unit: "per set of 2",
    category: "furniture",
    subcategory: "seating",
    brand: "Zuiver",
    styles: ["warm-contemporary"],
    roomTypes: ["kitchen", "living"],
    image: {
      id: "fur-08-img",
      name: "Dining Chair",
      type: "image",
      category: "furniture",
      subcategory: "seating",
      source: "unsplash",
      url: unsplash("1503602642458-232111445657"),
      color: "#D1FAE5",
      format: "jpg",
      tags: ["chair", "dining", "boucle", "oak"],
    },
    model3d: {
      id: "fur-08-3d",
      name: "Chair",
      type: "model3d",
      category: "furniture",
      subcategory: "seating",
      source: "local",
      modelPath: model("chair.glb"),
      format: "glb",
      tags: ["chair", "3d"],
    },
  },
  {
    id: "fur-09",
    name: "Dining Table Oak 160\u00D790",
    description: "Solid oak top, powder-coated steel legs, seats 6",
    price: 780,
    unit: "per unit",
    category: "furniture",
    subcategory: "table",
    brand: "Zuiver",
    styles: ["scandinavian", "warm-contemporary"],
    roomTypes: ["kitchen", "living"],
    image: {
      id: "fur-09-img",
      name: "Dining Table",
      type: "image",
      category: "furniture",
      subcategory: "table",
      source: "unsplash",
      url: unsplash("1533090481720-856c6e3c1fdc"),
      color: "#D2B48C",
      format: "jpg",
      tags: ["table", "dining", "oak", "kitchen"],
    },
    model3d: {
      id: "fur-09-3d",
      name: "Table",
      type: "model3d",
      category: "furniture",
      subcategory: "table",
      source: "local",
      modelPath: model("table.glb"),
      format: "glb",
      tags: ["table", "3d"],
    },
  },
  {
    id: "fur-10",
    name: "Queen Bed Frame with Headboard",
    description: "Upholstered linen headboard, solid wood slat base, 160\u00D7200 cm",
    price: 650,
    unit: "per unit",
    category: "furniture",
    subcategory: "bed",
    brand: "Noo.ma",
    styles: ["scandinavian", "warm-contemporary"],
    roomTypes: ["bedroom"],
    image: {
      id: "fur-10-img",
      name: "Queen Bed Frame",
      type: "image",
      category: "furniture",
      subcategory: "bed",
      source: "unsplash",
      url: unsplash("1505693416388-ac5ce068fe85"),
      color: "#E8DFD0",
      format: "jpg",
      tags: ["bed", "queen", "headboard", "bedroom"],
    },
    model3d: {
      id: "fur-10-3d",
      name: "Double Bed",
      type: "model3d",
      category: "furniture",
      subcategory: "bed",
      source: "local",
      modelPath: model("bedDouble.glb"),
      format: "glb",
      tags: ["bed", "3d"],
    },
  },
  {
    id: "fur-11",
    name: "Floor Lamp Arc",
    description: "Brushed brass arc floor lamp, marble base, fabric shade",
    price: 195,
    unit: "per unit",
    category: "furniture",
    subcategory: "lighting",
    styles: ["warm-contemporary", "scandinavian"],
    roomTypes: ["living", "bedroom"],
    image: {
      id: "fur-11-img",
      name: "Arc Floor Lamp",
      type: "image",
      category: "furniture",
      subcategory: "lighting",
      source: "unsplash",
      url: unsplash("1507473885765-e6ed057ab6fe"),
      color: "#FDE68A",
      format: "jpg",
      tags: ["lamp", "floor", "arc", "brass", "lighting"],
    },
    model3d: {
      id: "fur-11-3d",
      name: "Floor Lamp",
      type: "model3d",
      category: "furniture",
      subcategory: "lighting",
      source: "local",
      modelPath: model("lampRoundFloor.glb"),
      format: "glb",
      tags: ["lamp", "floor", "3d"],
    },
  },
  {
    id: "fur-12",
    name: "TV Console Unit",
    description: "Walnut veneer, two drawers, cable management, 150\u00D740\u00D755 cm",
    price: 420,
    unit: "per unit",
    category: "furniture",
    subcategory: "storage",
    brand: "String Furniture",
    styles: ["scandinavian", "warm-contemporary"],
    roomTypes: ["living"],
    image: {
      id: "fur-12-img",
      name: "TV Console",
      type: "image",
      category: "furniture",
      subcategory: "storage",
      source: "unsplash",
      url: unsplash("1556228453-efd6c1ff04f6"),
      color: "#8B6B4A",
      format: "jpg",
      tags: ["tv", "console", "storage", "walnut", "living"],
    },
  },

  // ── Plumbing & Electrical (12 products) ───────────────────
  {
    id: "plm-01",
    name: "Freestanding Bathtub",
    description: "Acrylic freestanding tub, white, 170\u00D775 cm, with drain",
    price: 890,
    unit: "per unit",
    category: "plumbing",
    subcategory: "plumbing",
    brand: "Ravak",
    roomTypes: ["bathroom"],
    image: {
      id: "plm-01-img",
      name: "Freestanding Bathtub",
      type: "image",
      category: "fixture",
      subcategory: "plumbing",
      source: "unsplash",
      url: unsplash("1584622650111-993a426fbf0a"),
      color: "#DBEAFE",
      format: "jpg",
      tags: ["bathtub", "freestanding", "bathroom", "acrylic"],
    },
    model3d: {
      id: "plm-01-3d",
      name: "Bathtub",
      type: "model3d",
      category: "fixture",
      subcategory: "plumbing",
      source: "local",
      modelPath: model("bathtub.glb"),
      format: "glb",
      tags: ["bathtub", "3d"],
    },
  },
  {
    id: "plm-02",
    name: "Single-Lever Basin Faucet",
    description: "Brushed nickel, ceramic cartridge, cold-start eco mode",
    price: 125,
    unit: "per unit",
    category: "plumbing",
    subcategory: "plumbing",
    brand: "Grohe",
    roomTypes: ["bathroom", "kitchen"],
    image: {
      id: "plm-02-img",
      name: "Basin Faucet",
      type: "image",
      category: "fixture",
      subcategory: "plumbing",
      source: "unsplash",
      url: unsplash("1585128792020-803d29415281"),
      color: "#CFFAFE",
      format: "jpg",
      tags: ["faucet", "basin", "nickel", "bathroom"],
    },
  },
  {
    id: "plm-03",
    name: "Ceramic Countertop Sink",
    description: "White glazed ceramic vessel basin, 50\u00D738 cm",
    price: 185,
    unit: "per unit",
    category: "plumbing",
    subcategory: "plumbing",
    brand: "Cersanit",
    roomTypes: ["bathroom"],
    image: {
      id: "plm-03-img",
      name: "Countertop Sink",
      type: "image",
      category: "fixture",
      subcategory: "plumbing",
      source: "unsplash",
      url: unsplash("1552321554-5fefe8c9ef14"),
      color: "#F3F4F6",
      format: "jpg",
      tags: ["sink", "ceramic", "vessel", "bathroom"],
    },
    model3d: {
      id: "plm-03-3d",
      name: "Bathroom Sink",
      type: "model3d",
      category: "fixture",
      subcategory: "plumbing",
      source: "local",
      modelPath: model("bathroomSink.glb"),
      format: "glb",
      tags: ["sink", "3d"],
    },
  },
  {
    id: "plm-04",
    name: "Wall-Hung Toilet",
    description: "Rimless wall-hung toilet with concealed cistern frame",
    price: 320,
    unit: "per unit",
    category: "plumbing",
    subcategory: "plumbing",
    brand: "Cersanit",
    roomTypes: ["bathroom"],
    image: {
      id: "plm-04-img",
      name: "Wall-Hung Toilet",
      type: "image",
      category: "fixture",
      subcategory: "plumbing",
      source: "unsplash",
      url: unsplash("1564078516393-cf04bd966897"),
      color: "#EDE9FE",
      format: "jpg",
      tags: ["toilet", "wall-hung", "rimless", "bathroom"],
    },
    model3d: {
      id: "plm-04-3d",
      name: "Toilet",
      type: "model3d",
      category: "fixture",
      subcategory: "plumbing",
      source: "local",
      modelPath: model("toilet.glb"),
      format: "glb",
      tags: ["toilet", "3d"],
    },
  },
  {
    id: "plm-05",
    name: "Thermostatic Shower Set",
    description: "Rain head 25 cm + hand shower, chrome, thermostatic valve",
    price: 295,
    unit: "per set",
    category: "plumbing",
    subcategory: "plumbing",
    brand: "Grohe",
    roomTypes: ["bathroom"],
    image: {
      id: "plm-05-img",
      name: "Shower Set",
      type: "image",
      category: "fixture",
      subcategory: "plumbing",
      source: "unsplash",
      url: unsplash("1620626011761-996317b8d101"),
      color: "#DBEAFE",
      format: "jpg",
      tags: ["shower", "thermostatic", "rain-head", "bathroom"],
    },
    model3d: {
      id: "plm-05-3d",
      name: "Shower",
      type: "model3d",
      category: "fixture",
      subcategory: "plumbing",
      source: "local",
      modelPath: model("shower.glb"),
      format: "glb",
      tags: ["shower", "3d"],
    },
  },
  {
    id: "plm-06",
    name: "Flush-Mount Outlet Pack",
    description: "Pack of 10 Schuko outlets, white, with child safety shutters",
    price: 48,
    unit: "per pack of 10",
    category: "plumbing",
    subcategory: "electrical",
    brand: "Legrand",
    image: {
      id: "plm-06-img",
      name: "Outlet Pack",
      type: "image",
      category: "fixture",
      subcategory: "electrical",
      source: "unsplash",
      url: unsplash("1558449028-b53a39d100fc"),
      color: "#FEF9C3",
      format: "jpg",
      tags: ["outlet", "electrical", "schuko", "safety"],
    },
  },
  {
    id: "plm-07",
    name: "Modular Light Switch Set",
    description: "Pack of 8 rocker switches, matt white, single-gang",
    price: 36,
    unit: "per pack of 8",
    category: "plumbing",
    subcategory: "electrical",
    brand: "Legrand",
    image: {
      id: "plm-07-img",
      name: "Light Switches",
      type: "image",
      category: "fixture",
      subcategory: "electrical",
      source: "unsplash",
      url: unsplash("1565538810643-b5bdb714032a"),
      color: "#F1F5F9",
      format: "jpg",
      tags: ["switch", "light", "electrical", "modular"],
    },
  },
  {
    id: "plm-08",
    name: "LED Ceiling Downlight Pack",
    description: "Pack of 6 recessed LED spots, 7 W each, warm white 3000 K",
    price: 85,
    unit: "per pack of 6",
    category: "plumbing",
    subcategory: "electrical",
    brand: "Philips",
    image: {
      id: "plm-08-img",
      name: "LED Downlights",
      type: "image",
      category: "fixture",
      subcategory: "electrical",
      source: "unsplash",
      url: unsplash("1524484485831-a92ffc0de03f"),
      color: "#FEF9C3",
      format: "jpg",
      tags: ["led", "downlight", "ceiling", "lighting"],
    },
  },
  {
    id: "plm-09",
    name: "Electric Water Heater 80 L",
    description: "Wall-mounted, enamel tank, 80 L, energy class B",
    price: 340,
    unit: "per unit",
    category: "plumbing",
    subcategory: "plumbing",
    brand: "Ariston",
    roomTypes: ["bathroom", "kitchen"],
    image: {
      id: "plm-09-img",
      name: "Water Heater",
      type: "image",
      category: "fixture",
      subcategory: "plumbing",
      source: "unsplash",
      url: unsplash("1585771724684-38269d6639fd"),
      color: "#FEE2E2",
      format: "jpg",
      tags: ["water-heater", "electric", "boiler"],
    },
  },
  {
    id: "plm-10",
    name: "Kitchen Mixer Faucet",
    description: "Pull-out spray head, matte black finish, swivel spout",
    price: 165,
    unit: "per unit",
    category: "plumbing",
    subcategory: "plumbing",
    brand: "Grohe",
    roomTypes: ["kitchen"],
    image: {
      id: "plm-10-img",
      name: "Kitchen Mixer Faucet",
      type: "image",
      category: "fixture",
      subcategory: "plumbing",
      source: "unsplash",
      url: unsplash("1584568694244-14fbdf83bd30"),
      color: "#1A202C",
      format: "jpg",
      tags: ["faucet", "kitchen", "mixer", "matte-black"],
    },
  },
  {
    id: "plm-11",
    name: "Split Air Conditioner 3.5 kW",
    description: "Inverter split unit, heating + cooling, energy class A++",
    price: 520,
    unit: "per unit",
    category: "plumbing",
    subcategory: "hvac",
    brand: "Daikin",
    roomTypes: ["living", "bedroom"],
    image: {
      id: "plm-11-img",
      name: "Split Air Conditioner",
      type: "image",
      category: "fixture",
      subcategory: "hvac",
      source: "unsplash",
      url: unsplash("1631545806609-05aba4c9ef04"),
      color: "#E2E8F0",
      format: "jpg",
      tags: ["air-conditioner", "hvac", "split", "inverter"],
    },
  },
  {
    id: "plm-12",
    name: "Distribution Panel 24-Way",
    description: "Flush-mount consumer unit, 24 modules, with RCD + MCBs",
    price: 95,
    unit: "per unit",
    category: "plumbing",
    subcategory: "electrical",
    brand: "Hager",
    image: {
      id: "plm-12-img",
      name: "Distribution Panel",
      type: "image",
      category: "fixture",
      subcategory: "electrical",
      source: "unsplash",
      url: unsplash("1621905252507-b35492cc74b4"),
      color: "#CBD5E0",
      format: "jpg",
      tags: ["panel", "distribution", "electrical", "circuit-breaker"],
    },
  },
];

/* ═══════════════════════════════════════════════════════════════
   3D MODEL REGISTRY — Maps furniture labels to GLB paths
   ═══════════════════════════════════════════════════════════════ */

export const MODEL_REGISTRY: Model3DAsset[] = [
  { id: "m-bed-double", name: "Double Bed", type: "model3d", category: "furniture", subcategory: "bed", source: "local", modelPath: model("bedDouble.glb"), format: "glb", tags: ["bed", "double", "bedroom"], dimensions: { width: 1.6, height: 0.5, depth: 2.0 } },
  { id: "m-bed-single", name: "Single Bed", type: "model3d", category: "furniture", subcategory: "bed", source: "local", modelPath: model("bedSingle.glb"), format: "glb", tags: ["bed", "single", "bedroom"], dimensions: { width: 0.9, height: 0.5, depth: 2.0 } },
  { id: "m-sofa", name: "Lounge Sofa", type: "model3d", category: "furniture", subcategory: "seating", source: "local", modelPath: model("loungeSofa.glb"), format: "glb", tags: ["sofa", "lounge", "living"], dimensions: { width: 2.0, height: 0.8, depth: 0.9 } },
  { id: "m-sofa-corner", name: "Corner Sofa", type: "model3d", category: "furniture", subcategory: "seating", source: "local", modelPath: model("loungeSofaCorner.glb"), format: "glb", tags: ["sofa", "corner", "living"], dimensions: { width: 2.4, height: 0.8, depth: 2.4 } },
  { id: "m-chair-lounge", name: "Lounge Chair", type: "model3d", category: "furniture", subcategory: "seating", source: "local", modelPath: model("loungeChair.glb"), format: "glb", tags: ["chair", "lounge", "living"] },
  { id: "m-chair", name: "Chair", type: "model3d", category: "furniture", subcategory: "seating", source: "local", modelPath: model("chair.glb"), format: "glb", tags: ["chair", "dining"] },
  { id: "m-chair-desk", name: "Desk Chair", type: "model3d", category: "furniture", subcategory: "seating", source: "local", modelPath: model("chairDesk.glb"), format: "glb", tags: ["chair", "desk", "office"] },
  { id: "m-desk", name: "Desk", type: "model3d", category: "furniture", subcategory: "table", source: "local", modelPath: model("desk.glb"), format: "glb", tags: ["desk", "office", "work"] },
  { id: "m-table", name: "Table", type: "model3d", category: "furniture", subcategory: "table", source: "local", modelPath: model("table.glb"), format: "glb", tags: ["table", "dining"] },
  { id: "m-table-round", name: "Round Table", type: "model3d", category: "furniture", subcategory: "table", source: "local", modelPath: model("tableRound.glb"), format: "glb", tags: ["table", "round", "dining"] },
  { id: "m-side-table", name: "Side Table", type: "model3d", category: "furniture", subcategory: "table", source: "local", modelPath: model("sideTable.glb"), format: "glb", tags: ["table", "side", "living"] },
  { id: "m-cabinet", name: "Bed Drawer Cabinet", type: "model3d", category: "furniture", subcategory: "storage", source: "local", modelPath: model("cabinetBedDrawer.glb"), format: "glb", tags: ["cabinet", "drawer", "bedroom"] },
  { id: "m-bath-sink", name: "Bathroom Sink", type: "model3d", category: "fixture", subcategory: "plumbing", source: "local", modelPath: model("bathroomSink.glb"), format: "glb", tags: ["sink", "bathroom"] },
  { id: "m-bathtub", name: "Bathtub", type: "model3d", category: "fixture", subcategory: "plumbing", source: "local", modelPath: model("bathtub.glb"), format: "glb", tags: ["bathtub", "bathroom"] },
  { id: "m-toilet", name: "Toilet", type: "model3d", category: "fixture", subcategory: "plumbing", source: "local", modelPath: model("toilet.glb"), format: "glb", tags: ["toilet", "bathroom"] },
  { id: "m-shower", name: "Shower", type: "model3d", category: "fixture", subcategory: "plumbing", source: "local", modelPath: model("shower.glb"), format: "glb", tags: ["shower", "bathroom"] },
  { id: "m-kitchen-sink", name: "Kitchen Sink", type: "model3d", category: "fixture", subcategory: "plumbing", source: "local", modelPath: model("kitchenSink.glb"), format: "glb", tags: ["sink", "kitchen"] },
  { id: "m-lamp-floor", name: "Floor Lamp", type: "model3d", category: "furniture", subcategory: "lighting", source: "local", modelPath: model("lampRoundFloor.glb"), format: "glb", tags: ["lamp", "floor", "lighting"] },
  { id: "m-lamp-table", name: "Table Lamp", type: "model3d", category: "furniture", subcategory: "lighting", source: "local", modelPath: model("lampRoundTable.glb"), format: "glb", tags: ["lamp", "table", "lighting"] },
  { id: "m-plant", name: "Potted Plant", type: "model3d", category: "furniture", subcategory: "decor", source: "local", modelPath: model("pottedPlant.glb"), format: "glb", tags: ["plant", "potted", "decor"] },
];

/* ═══════════════════════════════════════════════════════════════
   STYLE DIRECTION IMAGES — Moodboard & Inspiration
   ═══════════════════════════════════════════════════════════════ */

/** Hero images for style direction cards */
export const STYLE_HERO_IMAGES: Record<string, ImageAsset> = {
  scandinavian: {
    id: "style-scandi-hero",
    name: "Scandinavian Living",
    type: "image",
    category: "moodboard",
    source: "unsplash",
    url: unsplash("1586023492125-27b2c045efd7", { w: 600 }),
    format: "jpg",
    color: "#F5F3EF",
    tags: ["scandinavian", "hero", "living"],
  },
  industrial: {
    id: "style-industrial-hero",
    name: "Industrial Loft",
    type: "image",
    category: "moodboard",
    source: "unsplash",
    url: unsplash("1600607687939-ce8a6c25118c", { w: 600 }),
    format: "jpg",
    color: "#3A3A3A",
    tags: ["industrial", "hero", "loft"],
  },
  "warm-contemporary": {
    id: "style-warm-hero",
    name: "Warm Contemporary Living",
    type: "image",
    category: "moodboard",
    source: "unsplash",
    url: unsplash("1600210491892-03d54c0aaf87", { w: 600 }),
    format: "jpg",
    color: "#7B5B3A",
    tags: ["warm-contemporary", "hero", "living"],
  },
};

/* ═══════════════════════════════════════════════════════════════
   PORTFOLIO IMAGES — Built houses & case studies (future)
   ═══════════════════════════════════════════════════════════════ */

export const PORTFOLIO_IMAGES: ImageAsset[] = [
  // TODO: Add real built house photos when available
  // These will come from professional photography of completed ModulCA houses
  // For now, use high-quality modular house images from Unsplash
  {
    id: "port-01",
    name: "Modular Home Exterior",
    type: "image",
    category: "portfolio",
    source: "unsplash",
    url: unsplash("1600585154340-be6161a56a0c", { w: 800 }),
    format: "jpg",
    color: "#E8DFD0",
    tags: ["exterior", "modular", "house", "portfolio"],
  },
  {
    id: "port-02",
    name: "Contemporary Kitchen Interior",
    type: "image",
    category: "portfolio",
    source: "unsplash",
    url: unsplash("1600566753376-12c8ab7fb75b", { w: 800 }),
    format: "jpg",
    color: "#F5F3EF",
    tags: ["kitchen", "interior", "portfolio"],
  },
  {
    id: "port-03",
    name: "Nordic Bedroom",
    type: "image",
    category: "portfolio",
    source: "unsplash",
    url: unsplash("1600210492486-724fe5c67fb0", { w: 800 }),
    format: "jpg",
    color: "#D4B896",
    tags: ["bedroom", "interior", "portfolio"],
  },
];

/* ═══════════════════════════════════════════════════════════════
   LOCAL PRODUCT IMAGE OVERRIDES
   ═══════════════════════════════════════════════════════════════
   Maps product IDs to locally-hosted brand-attributed images
   downloaded by scripts/fetch-product-media.mjs.
   When a mapping exists, the local path overrides the Unsplash URL.
   ═══════════════════════════════════════════════════════════════ */

const LOCAL_IMAGE_OVERRIDES: Record<string, string> = {
  "fin-01": "/images/products/fin-01-oak-flooring.jpg",
  "fin-02": "/images/products/fin-02-gypsum-wall.jpg",
  "fin-04": "/images/products/fin-04-triple-window.jpg",
  "fin-05": "/images/products/fin-05-interior-door.jpg",
  "fin-06": "/images/products/fin-06-mineral-wool.jpg",
  "fin-08": "/images/products/fin-08-porcelain-tiles.jpg",
  "fin-10": "/images/products/fin-10-subway-tiles.jpg",
  "fin-11": "/images/products/fin-11-exterior-door.jpg",
  "fin-12": "/images/products/fin-12-countertop.jpg",
  "fur-01": "/images/products/fur-01-sofa.jpg",
  "fur-02": "/images/products/fur-02-rug.jpg",
  "fur-05": "/images/products/fur-05-shelving.jpg",
  "fur-06": "/images/products/fur-06-pendant.jpg",
  "fur-07": "/images/products/fur-07-mirror.jpg",
  "fur-08": "/images/products/fur-08-dining-chair.jpg",
  "plm-01": "/images/products/plm-01-bathtub.jpg",
  "plm-02": "/images/products/plm-02-faucet.jpg",
  "plm-03": "/images/products/plm-03-sink.jpg",
  "plm-04": "/images/products/plm-04-toilet.jpg",
  "plm-05": "/images/products/plm-05-shower.jpg",
};

/** Apply local image overrides to the catalog — called once at module load */
for (const product of PRODUCT_CATALOG) {
  const override = LOCAL_IMAGE_OVERRIDES[product.id];
  if (override) {
    product.image.url = override;
    product.image.source = "local";
  }
}

/* ═══════════════════════════════════════════════════════════════
   HELPER FUNCTIONS
   ═══════════════════════════════════════════════════════════════ */

/** Get a product by ID */
export function getProduct(id: string): ProductEntry | undefined {
  return PRODUCT_CATALOG.find((p) => p.id === id);
}

/** Get products by category */
export function getProductsByCategory(category: ProductEntry["category"]): ProductEntry[] {
  return PRODUCT_CATALOG.filter((p) => p.category === category);
}

/** Get products compatible with a style direction */
export function getProductsByStyle(styleId: string): ProductEntry[] {
  return PRODUCT_CATALOG.filter((p) => p.styles?.includes(styleId));
}

/** Get products relevant to a room type */
export function getProductsByRoom(roomType: string): ProductEntry[] {
  return PRODUCT_CATALOG.filter((p) => p.roomTypes?.includes(roomType));
}

/** Get a 3D model by label (fuzzy match, same logic as module3d.tsx) */
export function getModel3D(label: string): Model3DAsset | undefined {
  const lower = label.toLowerCase();
  // Exact tag match first
  const exact = MODEL_REGISTRY.find((m) => m.tags.some((t) => t === lower));
  if (exact) return exact;
  // Partial match
  return MODEL_REGISTRY.find((m) =>
    m.name.toLowerCase().includes(lower) ||
    m.tags.some((t) => lower.includes(t))
  );
}

/** Search all products by keyword */
export function searchProducts(query: string): ProductEntry[] {
  const q = query.toLowerCase();
  return PRODUCT_CATALOG.filter((p) =>
    p.name.toLowerCase().includes(q) ||
    p.description.toLowerCase().includes(q) ||
    p.image.tags.some((t) => t.includes(q)) ||
    p.brand?.toLowerCase().includes(q)
  );
}
