/**
 * ModulCA Asset Library — Type Definitions
 *
 * Unified type system for ALL visual assets across the platform:
 * product photos, material textures, moodboard images, furniture 3D models,
 * technical drawings, portfolio photos, producer brochures.
 */

/* ─── Image Sources ──────────────────────────────────────────── */

/** Where the image comes from — determines licensing & attribution */
export type AssetSource =
  | "unsplash"    // Free, requires attribution
  | "pexels"      // Free, no attribution required
  | "pixabay"     // Free, no attribution required
  | "local"       // Bundled in public/
  | "ai-generated"// Generated by AI render engines
  | "user-upload" // Uploaded by the user
  | "producer"    // From manufacturer/brand
  | "sketchfab"   // 3D model marketplace
  | "custom";     // Custom/other source

/** Asset file type */
export type AssetFormat = "jpg" | "png" | "webp" | "svg" | "glb" | "gltf" | "pdf" | "avif";

/* ─── Asset Categories ───────────────────────────────────────── */

/** Top-level category for organizing assets */
export type AssetCategory =
  | "material"     // Floor, wall, roof textures and swatches
  | "furniture"    // Furniture product photos + 3D models
  | "fixture"      // Plumbing, electrical, hardware
  | "portfolio"    // Built house photos, case studies
  | "moodboard"    // Style inspiration images
  | "technical"    // Technical drawings, construction details
  | "brochure"     // Producer catalogs, spec sheets
  | "render"       // AI-generated or 3D renders
  | "site"         // Landing page, marketing images
  | "icon";        // UI icons, badges

/** Sub-categories for finer organization */
export type MaterialSubcategory =
  | "flooring" | "wall-finish" | "tile" | "countertop"
  | "insulation" | "roofing" | "cladding" | "paint";

export type FurnitureSubcategory =
  | "seating" | "table" | "bed" | "storage" | "lighting"
  | "textile" | "decor" | "outdoor";

export type FixtureSubcategory =
  | "plumbing" | "electrical" | "hardware" | "hvac" | "window" | "door";

export type AssetSubcategory = MaterialSubcategory | FurnitureSubcategory | FixtureSubcategory | string;

/* ─── Core Asset Types ───────────────────────────────────────── */

/** Base asset definition — every asset in the library */
export interface Asset {
  id: string;
  name: string;
  category: AssetCategory;
  subcategory?: AssetSubcategory;
  source: AssetSource;
  /** Attribution text (required for Unsplash) */
  attribution?: string;
  /** Tags for search & filtering */
  tags: string[];
}

/** 2D image asset (photos, textures, renders) */
export interface ImageAsset extends Asset {
  type: "image";
  /** Base URL without size params — we append ?w=X&h=Y at render time */
  url: string;
  /** Thumbnail URL (smaller version for grids) */
  thumbUrl?: string;
  format: "jpg" | "png" | "webp" | "avif" | "svg";
  /** Dominant color for placeholder/skeleton */
  color?: string;
  /** Aspect ratio hint: "landscape" | "portrait" | "square" */
  aspect?: "landscape" | "portrait" | "square";
  width?: number;
  height?: number;
}

/** 3D model asset (GLB furniture, fixtures) */
export interface Model3DAsset extends Asset {
  type: "model3d";
  /** Path to GLB file (relative to public/) */
  modelPath: string;
  format: "glb" | "gltf";
  /** Preview image for 2D contexts */
  previewUrl?: string;
  /** Dimensions in meters */
  dimensions?: { width: number; height: number; depth: number };
}

/** Document asset (PDFs, brochures, spec sheets) */
export interface DocumentAsset extends Asset {
  type: "document";
  url: string;
  format: "pdf" | "png" | "jpg";
  /** Preview thumbnail */
  thumbUrl?: string;
  /** Number of pages (for PDFs) */
  pages?: number;
  /** File size in bytes */
  fileSize?: number;
}

/** Union of all asset types */
export type AnyAsset = ImageAsset | Model3DAsset | DocumentAsset;

/* ─── Product-specific types ─────────────────────────────────── */

/** A product in the marketplace with linked assets */
export interface ProductEntry {
  id: string;
  name: string;
  description: string;
  price: number;
  unit: string;           // "per m²", "per unit", "pack", etc.
  category: "finishing" | "furniture" | "plumbing";
  subcategory: AssetSubcategory;
  /** Brand/manufacturer name */
  brand?: string;
  /** Link to buy/view on supplier site */
  supplierUrl?: string;
  /** Primary product photo */
  image: ImageAsset;
  /** Additional gallery images */
  gallery?: ImageAsset[];
  /** Linked 3D model (if available) */
  model3d?: Model3DAsset;
  /** Technical spec sheet */
  specSheet?: DocumentAsset;
  /** Style compatibility */
  styles?: string[];      // ["scandinavian", "industrial", "warm-contemporary"]
  /** Module types this is relevant for */
  roomTypes?: string[];   // ["bedroom", "bathroom", "kitchen"]
  /** Color/material options */
  variants?: { label: string; color: string; image?: string }[];
}

/* ─── Collection types ───────────────────────────────────────── */

/** A curated collection of assets (e.g., "Scandinavian Kitchen" moodboard) */
export interface AssetCollection {
  id: string;
  name: string;
  description?: string;
  category: AssetCategory;
  style?: string;
  assets: AnyAsset[];
}

/* ─── Image URL helper types ─────────────────────────────────── */

export interface ImageSizeParams {
  w?: number;
  h?: number;
  q?: number;             // quality 1-100
  fit?: "crop" | "scale" | "clip";
}

/** Unsplash-specific params */
export interface UnsplashParams extends ImageSizeParams {
  fm?: "jpg" | "webp" | "avif";
  auto?: "format" | "compress";
}
