-- Migration 010: Monitoring signals + incidents + remediation log
--
-- Data model for the autonomous agent (Stage 1-4).
-- See docs/AUTONOMOUS_AGENT.md for architecture + rollout plan.
--
-- Idempotent. Safe to run multiple times.
-- Run in Supabase SQL Editor → paste + Run.
--
-- Tables added:
--   1. monitoring_signals — raw events from all data sources
--   2. incidents          — consolidated events needing human tracking
--   3. remediation_log    — every auto-action the agent took (Stage 3+)
--
-- RLS: service_role only. No anon/authenticated access.

-- ─────────────────────────────────────────────────────────────
-- 1. MONITORING SIGNALS (Stage 1 — always on)
-- ─────────────────────────────────────────────────────────────

create table if not exists public.monitoring_signals (
  id uuid default gen_random_uuid() primary key,
  created_at timestamptz not null default now(),

  -- Source of the signal (free-form string for flexibility)
  -- Examples: 'ops-check', 'sentry', 'stripe-webhook', 'supabase-query',
  --           'vercel-deploy', 'user-signup', 'ai-render', 'health-probe'
  source text not null,

  -- Severity — matches docs/AUTONOMOUS_AGENT.md classification matrix
  severity text not null default 'not-assessed'
    check (severity in ('not-assessed', 'normal', 'info', 'watch', 'warn', 'critical')),

  -- Human-readable short message (max 500 chars)
  message text not null check (length(message) <= 500),

  -- Structured payload (metrics, stack traces, query details, etc.)
  details jsonb not null default '{}'::jsonb,

  -- Deduplication fingerprint — same-type events collapse
  -- Generated by collector as e.g. sha256(source || '|' || message_template)
  fingerprint text,

  -- Link to consolidated incident (null = standalone signal)
  incident_id uuid references public.incidents(id) on delete set null,

  -- Agent processing state
  classified_at timestamptz,
  notified_at timestamptz,
  notified_channel text -- 'telegram' | 'email' | 'sentry' | null
);

-- Indexes for common query patterns
create index if not exists idx_monitoring_signals_created_at
  on public.monitoring_signals(created_at desc);
create index if not exists idx_monitoring_signals_severity
  on public.monitoring_signals(severity, created_at desc)
  where severity in ('warn', 'critical');
create index if not exists idx_monitoring_signals_source
  on public.monitoring_signals(source, created_at desc);
create index if not exists idx_monitoring_signals_fingerprint
  on public.monitoring_signals(fingerprint)
  where fingerprint is not null;
create index if not exists idx_monitoring_signals_incident
  on public.monitoring_signals(incident_id)
  where incident_id is not null;

-- ─────────────────────────────────────────────────────────────
-- 2. INCIDENTS (Stage 2+ — consolidated events)
-- ─────────────────────────────────────────────────────────────

create table if not exists public.incidents (
  id uuid default gen_random_uuid() primary key,
  opened_at timestamptz not null default now(),
  closed_at timestamptz,

  severity text not null default 'watch'
    check (severity in ('info', 'watch', 'warn', 'critical')),

  title text not null check (length(title) <= 200),
  description text,

  status text not null default 'open'
    check (status in ('open', 'acknowledged', 'remediated', 'closed', 'post-mortem-pending', 'closed-no-action')),

  resolution text,

  -- Who acknowledged/closed (email or 'agent' for automated)
  human_ack_by text,
  human_ack_at timestamptz,

  -- Link to post-mortem document if required
  post_mortem_path text,

  -- How long before human acknowledgment (computed at ack time)
  time_to_ack_seconds integer,

  -- How long from open to close
  time_to_close_seconds integer
);

create index if not exists idx_incidents_status
  on public.incidents(status, opened_at desc)
  where status != 'closed';
create index if not exists idx_incidents_severity
  on public.incidents(severity, opened_at desc);
create index if not exists idx_incidents_opened_at
  on public.incidents(opened_at desc);

-- Auto-update time_to_close when status changes to closed
create or replace function public.incidents_update_times()
returns trigger language plpgsql as $$
begin
  if new.status = 'acknowledged' and old.status = 'open' and new.human_ack_at is null then
    new.human_ack_at := now();
    new.time_to_ack_seconds := extract(epoch from (now() - new.opened_at))::integer;
  end if;
  if new.status in ('closed', 'closed-no-action') and new.closed_at is null then
    new.closed_at := now();
    new.time_to_close_seconds := extract(epoch from (now() - new.opened_at))::integer;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_incidents_update_times on public.incidents;
create trigger trg_incidents_update_times
  before update on public.incidents
  for each row execute function public.incidents_update_times();

-- ─────────────────────────────────────────────────────────────
-- 3. REMEDIATION LOG (Stage 3+ — auto-actions audit trail)
-- ─────────────────────────────────────────────────────────────

create table if not exists public.remediation_log (
  id uuid default gen_random_uuid() primary key,
  created_at timestamptz not null default now(),
  incident_id uuid references public.incidents(id) on delete set null,

  -- Playbook that triggered this action
  playbook_name text not null,

  -- Action classification
  action_type text not null
    check (action_type in ('config_change', 'fallback', 'restart', 'cache_purge',
                           'rate_limit', 'engine_disable', 'notify_only',
                           'escalate', 'circuit_break')),

  -- Full action payload
  action_details jsonb not null default '{}'::jsonb,

  -- Did the action succeed technically?
  success boolean not null default true,

  -- Did a human have to undo this action? (critical signal — bad playbook)
  human_reversed boolean not null default false,
  human_reversed_at timestamptz,
  human_reversed_by text,
  human_reversed_reason text,

  -- Notes (LLM reasoning, context, etc.)
  notes text
);

create index if not exists idx_remediation_log_incident
  on public.remediation_log(incident_id, created_at desc);
create index if not exists idx_remediation_log_playbook
  on public.remediation_log(playbook_name, created_at desc);
create index if not exists idx_remediation_log_reversed
  on public.remediation_log(human_reversed, created_at desc)
  where human_reversed = true;

-- ─────────────────────────────────────────────────────────────
-- 4. RLS — service_role only (no anon/authenticated access)
-- ─────────────────────────────────────────────────────────────

alter table public.monitoring_signals enable row level security;
alter table public.incidents enable row level security;
alter table public.remediation_log enable row level security;

-- service_role full access
drop policy if exists "Service role full access monitoring_signals" on public.monitoring_signals;
create policy "Service role full access monitoring_signals"
  on public.monitoring_signals for all
  using (auth.jwt() ->> 'role' = 'service_role');

drop policy if exists "Service role full access incidents" on public.incidents;
create policy "Service role full access incidents"
  on public.incidents for all
  using (auth.jwt() ->> 'role' = 'service_role');

drop policy if exists "Service role full access remediation_log" on public.remediation_log;
create policy "Service role full access remediation_log"
  on public.remediation_log for all
  using (auth.jwt() ->> 'role' = 'service_role');

-- Explicitly REVOKE from public/anon/authenticated for safety
revoke all on public.monitoring_signals from public, anon, authenticated;
revoke all on public.incidents from public, anon, authenticated;
revoke all on public.remediation_log from public, anon, authenticated;

-- ─────────────────────────────────────────────────────────────
-- 5. HELPER FUNCTIONS (used by collector + dashboard)
-- ─────────────────────────────────────────────────────────────

-- Insert signal with dedup — called by monitor-collect.mjs via RPC
create or replace function public.agent_insert_signal(
  p_source text,
  p_severity text,
  p_message text,
  p_details jsonb default '{}'::jsonb,
  p_fingerprint text default null,
  p_dedup_window_minutes integer default 5
)
returns uuid
language plpgsql security definer set search_path = public
as $$
declare
  v_existing_id uuid;
  v_new_id uuid;
begin
  -- Dedup: if same fingerprint seen in last N minutes, skip insertion
  if p_fingerprint is not null then
    select id into v_existing_id
    from monitoring_signals
    where fingerprint = p_fingerprint
      and created_at > now() - (p_dedup_window_minutes || ' minutes')::interval
    order by created_at desc
    limit 1;

    if v_existing_id is not null then
      return v_existing_id;  -- dedup hit
    end if;
  end if;

  -- Insert fresh signal
  insert into monitoring_signals (source, severity, message, details, fingerprint)
  values (p_source, p_severity, p_message, p_details, p_fingerprint)
  returning id into v_new_id;

  return v_new_id;
end;
$$;

-- Get active incidents (for dashboard + Telegram /incidents command)
create or replace function public.agent_active_incidents(limit_n integer default 20)
returns table (
  id uuid,
  opened_at timestamptz,
  severity text,
  title text,
  status text,
  age_minutes integer,
  signal_count bigint
)
language plpgsql security definer set search_path = public
as $$
begin
  return query
  select
    i.id,
    i.opened_at,
    i.severity,
    i.title,
    i.status,
    extract(epoch from (now() - i.opened_at))::integer / 60 as age_minutes,
    count(s.id) as signal_count
  from incidents i
  left join monitoring_signals s on s.incident_id = i.id
  where i.status not in ('closed', 'closed-no-action')
  group by i.id
  order by
    case i.severity
      when 'critical' then 1
      when 'warn' then 2
      when 'watch' then 3
      else 4
    end,
    i.opened_at desc
  limit limit_n;
end;
$$;

-- Get recent signals by severity (for dashboard tile)
create or replace function public.agent_recent_signals(
  p_min_severity text default 'watch',
  p_hours integer default 24,
  p_limit integer default 50
)
returns table (
  id uuid,
  created_at timestamptz,
  source text,
  severity text,
  message text,
  incident_id uuid
)
language plpgsql security definer set search_path = public
as $$
declare
  v_severity_levels text[] := array['normal', 'info', 'watch', 'warn', 'critical'];
  v_min_index integer;
begin
  v_min_index := array_position(v_severity_levels, p_min_severity);

  return query
  select s.id, s.created_at, s.source, s.severity, s.message, s.incident_id
  from monitoring_signals s
  where s.created_at > now() - (p_hours || ' hours')::interval
    and array_position(v_severity_levels, s.severity) >= v_min_index
  order by s.created_at desc
  limit p_limit;
end;
$$;

-- Stats snapshot (for Telegram /status + dashboard overview)
create or replace function public.agent_health_snapshot()
returns jsonb
language plpgsql security definer set search_path = public
as $$
declare
  result jsonb;
begin
  select jsonb_build_object(
    'snapshot_at', now(),
    'last_24h_signals', (
      select count(*) from monitoring_signals
      where created_at > now() - interval '24 hours'
    ),
    'last_24h_by_severity', (
      select jsonb_object_agg(severity, cnt)
      from (
        select severity, count(*) as cnt
        from monitoring_signals
        where created_at > now() - interval '24 hours'
        group by severity
      ) t
    ),
    'open_incidents', (
      select count(*) from incidents
      where status not in ('closed', 'closed-no-action')
    ),
    'critical_open', (
      select count(*) from incidents
      where status not in ('closed', 'closed-no-action')
        and severity = 'critical'
    ),
    'last_critical', (
      select jsonb_build_object('title', title, 'opened_at', opened_at)
      from incidents
      where severity = 'critical'
      order by opened_at desc
      limit 1
    ),
    'recent_remediations_24h', (
      select count(*) from remediation_log
      where created_at > now() - interval '24 hours'
    ),
    'reversed_remediations_24h', (
      select count(*) from remediation_log
      where created_at > now() - interval '24 hours' and human_reversed = true
    )
  ) into result;

  return result;
end;
$$;

-- Grants — service_role only
grant execute on function public.agent_insert_signal(text, text, text, jsonb, text, integer) to service_role;
grant execute on function public.agent_active_incidents(integer) to service_role;
grant execute on function public.agent_recent_signals(text, integer, integer) to service_role;
grant execute on function public.agent_health_snapshot() to service_role;

revoke execute on function public.agent_insert_signal(text, text, text, jsonb, text, integer) from public, anon, authenticated;
revoke execute on function public.agent_active_incidents(integer) from public, anon, authenticated;
revoke execute on function public.agent_recent_signals(text, integer, integer) from public, anon, authenticated;
revoke execute on function public.agent_health_snapshot() from public, anon, authenticated;

-- Done. Run `npm run db:analyze` later to verify.
